### ISSUE TITLE
Update for authoring tool

### ISSUE THREAD

**Issue by dancgray** [ExultCorp/adapt-contrib-flipcard#1]
I'd like to update this component so it can be used with the authoring tool. Happy to create the schema file.

**Comment by dancgray** [comment]
@hrajotia it might be preferable to have backListOfOptions as a text string rather than an array. So that a RTE can be used in the authoring tool. How do you feel about changing this?

**Comment by himanshu1618** [comment]
@dancgray - Apology for the delayed response. I've made few enhancement to this repo and also have added the [properties.schema](https://github.com/ExultCorp/adapt-contrib-flipCard/blob/master/properties.schema), additionally updated the [example.json](https://github.com/ExultCorp/adapt-contrib-flipCard/blob/master/example.json) as you've suggested to me.
Can you have a look on this as you understand those schema better.

Thanks!
